steps:
- name: 'docker.io/library/python:3.10'
  entrypoint: /bin/sh
  args: [-c, 'pip install -r requirements.txt']
  dir: 'prepare_form'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'guest', '--trigger-http', '--runtime', 'python310']
  dir: 'prepare_form'
options:
  logging: CLOUD_LOGGING_ONLY
